### ISSUE TITLE
Customize simulator devices behavior 

### ISSUE THREAD

**Issue by SatyaaDixit** [awslabs/iot-device-simulator#16]
Need to perform major testing with heavy load. 
• Possibility to start more than 100 simulations at a time?
• When starting more than 1000 sensors simulators most of them remain in provisioning mode and after stopping the running simulators then only provisioning simulators are being started as expected behavior but can start up to 10000 or more simulations?
 ++ **Device count and data interval limitations** also on time interval?

**Comment by gsingh04** [comment]
Thanks for your query.

Can you follow the instructions [here](https://docs.aws.amazon.com/solutions/latest/iot-device-simulator/appendix-e.html) and try with an increased number of task count. More task count should be able to support higher number of simulations simultaneously. Let us know if this helps!

**Comment by SatyaaDixit** [comment]
Thanks @gsingh04 let me check this .

**Comment by maykays** [comment]
Closing issue. Please re-open if the issue persists.
