### ISSUE TITLE
The static value in Type config stored as String but should be Bool

### ISSUE THREAD

**Issue by c3gdlk** [awslabs/iot-device-simulator#5]
I've installed a new instance from the official template and faced with an issue when UUID Attributes of Type are not unique. I've found out the reason - the false value stored as String "false" while it expects a Bool value

I had to change it manually via DynamoDB console from String to Bool to make it works.

**Comment by shsenior** [comment]
@c3gdlk thanks for the feedback. We have this fixed in an upcoming release this quarter with several new additional features.

**Comment by shsenior** [comment]
Updated in version 2.1.0
