### ISSUE TITLE
Allow for creation of more than 25 widgets

### ISSUE THREAD

**Issue by massi-ang** [awslabs/iot-device-simulator#6]
Let the user specify any amount of widgets up to 1000 and have the backend limit the concurrent creation to 25 at the time to stay in the DynamoDB WCU limit

**Comment by shsenior** [comment]
@massi-ang Thanks for the feedback. We are adding the ability to create 100 widgets at a time with the upcoming release this quarter.

**Comment by shsenior** [comment]
Updated in version 2.1.0
