### ISSUE TITLE
Add the possibility to use attribute values and device Id as part of the topic

### ISSUE THREAD

**Issue by massi-ang** [awslabs/iot-device-simulator#7]
This would allow to create more generic device types

**Comment by shsenior** [comment]
@massi-ang Thanks for the feedback. We are looking into adding the device id as part of the topic for the upcoming release this quarter. 

example. 
/turbine/telemetry/{deviceId} would be translated to /turbine/telemetry/AQcDCAgJDg0 for widget AQcDCAgJDg0

We will add the ability to use attribute values to the backlog.

**Comment by shsenior** [comment]
Updated in version 2.1.0

**Comment by aloysiustany** [comment]
@shsenior I am running iot-device-simulator/v2.1.1 and it does not seem to work. 
$aws/rules/staging_health/sensors/{deviceId} gets sent as is without replacing the {deviceId} value.

**Comment by SootyOwl** [comment]
Is this still possible or has the feature been removed? I'm unable to find any documentation referencing this and the changelogs describing how to use the feature have been removed in subsequent commits.
