### ISSUE TITLE
no modify run test error 

### ISSUE THREAD

**Issue by bobogogo1990** [awslabs/iot-device-simulator#9]
![image](https://user-images.githubusercontent.com/15936679/55664245-ecd38a00-585d-11e9-920f-444e2c33dba3.png)

my nodejs version: v10.12.0

thanks a lot

**Comment by tomnight** [comment]
Hi there,
I just tried the run_unit_test.sh script on my local machine and everything passed successfully.  OSX nodejs v10.14.1

Did you run the test script or are you running npm test?

**Comment by maykays** [comment]
Closing this issue due to lack of response. Please re-open if you continue to face this issue.
